### ISSUE TITLE
React-snap failing on AWS Amplify

### ISSUE THREAD

**Issue by thinkJin6** [thinkJin6/BokuNews#64]
**Describe the bug**

The Codes run perfectly well in localhost. But when pushing it up to `AWS amplify`, the build fails.

<img width="982" alt="Screen Shot 2021-09-20 at 7 30 03 PM" src="https://user-images.githubusercontent.com/73213945/133988860-e3f0e04c-803b-41c9-a09e-d7f5941d8318.png">

**To Reproduce**

**Step 1**: Add the following steps to your `amplify.yml` config file to install Chrome
```
frontend:
  phases:
    preBuild:
      commands:
        - '# This installs Chrome on any RHEL/CentOS/Amazon Linux variant.'
        - curl https://intoli.com/install-google-chrome.sh | bash
```

**Step 2**: Add the following configuration to your `package.json`
```
'reactSnap': {
    'puppeteerArgs': ['--no-sandbox', '--disable-setuid-sandbox'],
    'puppeteerExecutablePath': '/opt/google/chrome/google-chrome'
  }
```

**Reference**

[https://github.com/puppeteer/puppeteer/issues/765#issuecomment-445334163](https://github.com/puppeteer/puppeteer/issues/765#issuecomment-445334163)
